[package]
name = "fun-with-flags"
version = "0.1.0"
authors = ["Thomas <thomastimmer11@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
sha2 = "0.9.0"
rand = "0.7.3"
mockall = "0.7.1"
cfg-if = "0.1.10"
lazy_static = "1.4.0"

[dev-dependencies]
diesel_migrations = "*"
serial_test = "*"