[package]
name = "fun-with-flags"
version = "0.1.0"
authors = ["Thomas <thomastimmer11@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"], optional = true }
diesel_migrations = { version = "1.4", optional = true }
dotenv = "0.15.0"
sha2 = "0.9.0"
rand = "0.7.3"
mockall = "0.7.1"
cfg-if = "0.1.10"
lazy_static = "1.4.0"
r2d2 = {version = "0.8.9", optional = true}
redis = {version = "0.16.0", features = ["r2d2", "cluster"], optional = true}

[dev-dependencies]
serial_test = "*"

[features]
redis-backend = ["r2d2", "redis"]
postgres-backend = ["diesel", "diesel_migrations"]

[[example]]
name = "postgres"
required-features = ["postgres-backend"]