version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=username 
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=username 
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3306:3306
      - 33060:33060
  redis:
    image: redis
    ports:
      - 6379:6379
