name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d
    - name: Build
      run: cargo build --verbose
    - name: Run tests (unit)
      run: bash ./test.sh unit
    - name: Run tests (postgres)
      run: bash ./test.sh postgres
    - name: Run tests (redis)
      run: bash ./test.sh redis
    - name: Run tests (cached postgres)
      run: bash ./test.sh postgres-c
    - name: Run tests (cached redis)
      run: bash ./test.sh redis-c
