name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d
    - name: Build
      run: cargo build --verbose
  unit:
    runs-on: ubuntu-latest
    needs: startup
    steps:
    - name: Run tests (unit)
      run: bash ./test_unit.sh
  postgres:
    runs-on: ubuntu-latest
    needs: startup
    steps:
    - name: Run tests (postgres)
      run: bash ./test_postgres.sh
  redis:
    runs-on: ubuntu-latest
    needs: startup
    steps:
    - name: Run tests (redis)
      run: bash ./test_redis.sh
