name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d
    - name: Build
      run: cargo build --verbose
    - name: Run tests (postgres)
      run: ./test_postgres.sh
    - name: Run tests (redis)
      run: ./test_redis.sh
